### REDDIT WORKS ON LOCAL MACHINE BUT NOT IN DOCKER
agents:
#  - image-generator
#  - pictory
#  - copy-files-to-pictory-output
#  - subtitles-translation
  - translation
#  - youtube
#  - blog
#  - twitter
#  - facebook
#  - instagram
#  - tiktok
#  - reddit

# input

# Optional. Used for title and description. Either set this, or provide a text-title and text-content
text-file: ${HOME}/.aideas/content/for-translation.txt

# Optional. If not set, the name (without extension) of text-file will be used
#text-title:

# Optional. If not set, the content of text-file will be used
#text-content:

#image-file-landscape:

# Optional. If not set, image-file-landscape will be used
#image-file-square:

share-cover-image: true

# Optional. Possible values: visible|undetected
browser-mode:

#input-language-code:

#language-codes:
