### REDDIT WORKS ON LOCAL MACHINE BUT NOT IN DOCKER
agents:
#  - image-generator
#  - pictory
#  - copy-files-to-pictory-output
  - subtitles-translation
#  - youtube
#  - blog
#  - twitter
#  - facebook
#  - instagram
#  - tiktok
#  - reddit

# input
#############################################################################
# If running in docker (usually the case)
# These can be full paths, because we are mounting their directory in docker
# They must however be contained within our CONTENT_DIR
# See environment variables for CONTENT_DIR
#############################################################################

language-codes: en

# Optional. Used for title and description. Either set this, or provide a text-title and text-content
#text-file:

# Optional. If not set, the name (without extension) of text-file will be used
#text-title:

# Optional. If not set, the content of text-file will be used
#text-content:

#image-file-landscape:

# Optional. If not set, image-file-landscape will be used
#image-file-square:

share-cover-image: true

# Optional. Possible values: visible|undetected
browser-mode: