stages:
  login:
    url: https://www.reddit.com/login/
    stage-items:
      enter-user-name:
        search-for: //*[@id="login-username"]
        actions: enter_text $REDDIT_USER_NAME
      enter-password:
        search-for: //*[@id="login-password"]
        actions:
          - enter_text $REDDIT_USER_PASS
          - wait 2 # The button becomes clickable after both are entered
      # The target element resides within a shadow DOM, XPath will not work.
      # See: https://stackoverflow.com/questions/37384458/how-to-handle-elements-inside-shadow-dom-from-selenium
      # See: https://stackoverflow.com/questions/77636171/i-cant-click-log-in-button-in-reddit-login-screen-with-selenium
      submit-login:
        search-for:
          shadow-attributes: slot=primaryButton
        actions:
          - click
          - wait 8 # Login takes a while
  cookies:
    stage-items:
      reject-non-essential-cookies:
        events:
          onerror: continue
        search-from:
          shadow-attributes: id=reject-nonessential-cookies-button
        search-for: /button[contains(text(), "Reject")]
        actions:
          - click
          - wait 2
  dismiss-cookie-alert:
    url: https://www.reddit.com/r/${REDDIT_COMMUNITY_NAME}/submit
    stage-items:
      reject-non-essential-cookies:
        wait-timeout-seconds: 10
        events:
          onerror: continue
        search-for:
          - //*[@id="SHORTCUT_FOCUSABLE_DIV"]/div[3]/div/section/div/section[2]/section[2]/form/button
          - //*[@id="SHORTCUT_FOCUSABLE_DIV"]//form/button[contains(text(), "Reject")]
          - //button[contains(text(), "Reject non-essential")]
  dismiss-collection-alert:
    stage-items:
      dismiss-collection-alert-by-clicking-x:
        wait-timeout-seconds: 10
        events:
          onerror: continue
        search-for: //*[@id="SHORTCUT_FOCUSABLE_DIV"]//*[name()="svg"]
      dismiss-collection-alert-by-clicking-cancel:
        wait-timeout-seconds: 5
        events:
          onerror: continue
        search-for: //*[@id="SHORTCUT_FOCUSABLE_DIV"]/div[4]/div/div/div/footer/div/button[1]
  title:
    url: https://www.reddit.com/r/${REDDIT_COMMUNITY_NAME}/submit
    stage-items:
      enter-title:
        search-for:
          - //*[@id="AppRouter-main-content"]//textarea[@placeholder="Title"]
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[1]/div/textarea
          - //*[@id="AppRouter-main-content"]//textarea[@rows="1"]
        actions: enter_text $VIDEO_TITLE
  cover-image:
    events:
      onerror: continue
    stage-items:
      add-cover-image:
        search-for:
          - //*[@id="AppRouter-main-content"]//button[contains(@aria-label, "image")]/input[@type="file"]
          - //*[@id="AppRouter-main-content"]//button/input[@type="file"]
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[1]/div[1]/div/span[16]/button/input[@type="file"]
        actions:
          - enter_text $VIDEO_COVER_IMAGE
          - wait 5
      enter-cover-image-caption:
        search-for:
          # //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div[2]/div/div/span
          - //*[@id="AppRouter-main-content"]//div[contains(@style, "Add caption")]
          - //*[@id="AppRouter-main-content"]//*[contains(@style, "Add caption")]
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div[2]
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div[2]/div
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div[2]/div/div
        actions:
          - enter_text $VIDEO_TITLE
          - wait 2
  content:
    stage-items:
      enter-content:
        search-for:
          # //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div/div[1]/div
          - //*[@id="AppRouter-main-content"]//div[@class="DraftEditor-root"]//div[@role="textbox"]
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div/div/div/div/div[1]
          - //*[@id="AppRouter-main-content"]//div[@role="textbox"]
        actions:
          - move_to_element
          - enter
          - enter_text $VIDEO_DESCRIPTION
          - wait 2
  post:
    stage-items:
      post-content:
        search-for:
          - //*[@id="AppRouter-main-content"]/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div[3]/div[2]/div/div/div[1]/button[1]
          # This led us to another button
          #- //*[@id="AppRouter-main-content"]//button[contains(text(), "Post")]
          # This did not find anything
          #- //*[@id="AppRouter-main-content"]//button[@role="button" and tabindex="0" and text()="Post"]
        actions:
          # This is necessary, because the button is usually not visible, after pasting the content
          # move_to_element should scroll the element into view
          - move_to_element
          - wait 2
          - click
          - wait 10
  approve-post:
    url: https://www.reddit.com/r/${REDDIT_COMMUNITY_NAME}/
    events:
      onerror: log WARNING \n= = = = = = = FAILED TO APPROVE POST (Please do it manually) = = = = = = =\n
    stage-items:
      approve-post:
        search-for:
          - //*[@id="t3_1bovvsu"]/shreddit-mod-inline-actions//mod-action-button[1]
          # This did not work
          # shadow-attributes: aria-label="Approve content"
        actions:
          - click
          - wait 2



