browser:
  chrome:
    undetected: true
    options:
      args:
        - user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
        # Use either (headless and start-maximized) or kiosk
        # Trying to change window size, while using kiosk, will crash the driver
        # Without this custom window size, we got ElementNotInteractableException
        # Window size should match that in docker-entrypoint.sh
        - window-size=1920,1080
        - start-maximized
depends-on:
  - youtube
subtitles:
  #"ar", "bn", "de", "es", "fr", "hi", "it", "ja", "ko", "ru", "zh", "zh-TW"
  languages:
    - code: de
      name: German
    - code: fr
      name: French
    - code: es
      name: Spanish
    - code: it
      name: Italian
    - code: ru
      name: Russian
    - code: ja
      name: Japanese
    - code: ko
      name: Korean
    - code: zh
      name: Chinese
    - code: ar
      name: Arabic
    - code: hi
      name: Hindi
stages:
  login:
    events:
      onstart: run_stages youtube.login
      onsuccess: log INFO Logged in to YouTube
