version: '3.8'
services:
  aideas:
    image: "poshjosh/aideas:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: ./src/python/main/app
      dockerfile: ../Dockerfile
    shm_size: '2gb'
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./src/python/main/resources
        target: /resources
      - type: bind
        source: ${DOCKER_MOUNT_DIR}
        target: ${DOCKER_MOUNT_DIR}
