version: '3.8'
services:
  aideas:
    image: "poshjosh/aideas:${APP_VERSION:-latest}"
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t
    build:
      context: src/aideas
      dockerfile: ../../Dockerfile
    expose:
      - "${APP_PORT:-5000}"
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    shm_size: '2gb'
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-1}
      APP_PORT: "${APP_PORT:-5000}"
      APP_PROFILES: "docker,${APP_PROFILES:-default}"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock