version: '3.8'
services:
  aideas:
    build:
      context: ./src/python/main/app
      dockerfile: ../Dockerfile
    shm_size: '2gb'
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./src/python/main/resources
        target: /resources
      - type: bind
        source: /Users/chinomso/Desktop/live-above-3D/eternity-is-not-kind
        target: /Users/chinomso/Desktop/live-above-3D/eternity-is-not-kind
