version: '3.8'
services:
  aideas:
    image: "poshjosh/aideas:${APP_VERSION:-latest}"
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t
    build:
      context: src/aideas
      dockerfile: ../../Dockerfile
    expose:
      - "${APP_PORT:-5000}"
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    shm_size: '2gb'
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-1}
      APP_PROFILES: ${APP_PROFILES:-docker}
      APP_PORT: "${APP_PORT:-5000}"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./src/resources
        target: /aideas/resources # must be within our WORKDIR (i.e. 'aideas')
      - type: bind
        source: ${CONTENT_DIR}
        target: ${CONTENT_DIR}
      - type: bind
        source: ${BROWSER_PROFILE_DIR}
        target: ${BROWSER_PROFILE_DIR}
      - type: bind
        # TODO - This should be dynamic. By the way it is only required by the blog agent
        source: ./src/resources/output/blog-app/app/automate-jamstack-0.0.9/app
        target: /aideas/blog-app # must be within our WORKDIR (i.e. 'aideas')
