# For undetected browser, some options and prefs cause some websites
# (e.g. YouTube) to detect the browser as a bot. Therefore, we use:
# minimal options e.g: window-size,start-maximized,user-agent
# minimal prefs e.g: download.default_directory
app:
  name: aideas
  agent:
    timeout-seconds: 20
browser:
  chrome:
#    executable_path:
    undetected: false
    prefs:
      intl.accept_languages: en-GB
      # prevent credentials based popups (e.g. save password popups)
      credentials_enable_service: false
      profile.password_manager_enabled: false
      # prevent general popups
      profile.managed_default_content_settings.popups : 2
      profile.default_content_setting_values.notifications: 2
      download.prompt_for_download: false
      directory_upgrade: true
      safebrowsing.enabled: false
    options:
      args:
        - lang=en-GB
        - no-sandbox
        - disable-setuid-sandbox
        - disable-application-cache
        - disable-dev-shm-usage  # We have shm_size: 2g, specified in docker-compose.yml
        - disable-notifications
        - enable-javascript
        - user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
        - disable-infobars
        - disable-extensions
        # Use either (headless and start-maximized) or kiosk
        # Trying to change window size, while using kiosk, will crash the driver
        # Without this custom window size, we got ElementNotInteractableException
        # Window size should match that in docker-entrypoint.sh
        - window-size=1920,1080
        - start-maximized
        - headless
        - disable-web-security
        - allow-running-insecure-content
#        Location where chrome stores profiles
#        - user-data-dir=/Users/chinomso/Library/Application Support/Google/Chrome
#        Location relative to user-data-dir where chrome profile to be used is stored
#        - profile-directory=Default
#        - remote-allow-origins=*
#        - remote-debugging-port=9222
#        - incognito
#        - crash-dumps-dir=/tmp

agents:
  - image-generator
  - pictory
  - translation
  - youtube
  - blog
  - twitter
  - reddit
  - facebook
  - instagram
  - tiktok


