### REDDIT WORKS ON LOCAL MACHINE BUT NOT IN DOCKER
agents:
#  - image-generator
#  - pictory
#  - copy-files-to-pictory-output
  - translation
#  - youtube
#  - blog
#  - twitter
#  - facebook
#  - instagram
#  - tiktok
#  - reddit

# video input
#############################################################################
# If running in docker (usually the case)
# These can be full paths, because we are mounting their directory in docker
# They must however be contained within our CONTENT_DIR
# See environment variables for CONTENT_DIR
#############################################################################
# Optional. Used for title and description. Either set this, or provide a title and description
video-content-file: "/Users/chinomso/Desktop/live-above-3D/a-shadow-of-the-real-world/A shadow of the real world.txt"

# Optional. Used for suffix to append to the description. If not set, description-suffix will be used
#video-content-suffix-file:

# Optional. If not set, the name (without extension) of video-content-file will be used
#video-title:

# Optional. If not set, the content of video-content-file will be used
#video-content:

# Optional. If not set, the content of video-content-suffix-file will be used.
video-content-suffix: "#christ #avatar #videogame #nomoregames #jesus #christian #love #faith #yahweh #god"

video-cover-image: /Users/chinomso/Desktop/live-above-3D/a-shadow-of-the-real-world/cover.jpg

# Optional. If not set, video-cover-image will be used
video-cover-image-square: /Users/chinomso/Desktop/live-above-3D/a-shadow-of-the-real-world/cover-square.jpg
