# Lots of shadow DOM elements here. When the target element resides
# within a shadow DOM, XPath will not work.
# See: https://stackoverflow.com/questions/37384458/how-to-handle-elements-inside-shadow-dom-from-selenium
# See: https://stackoverflow.com/questions/77636171/i-cant-click-log-in-button-in-reddit-login-screen-with-selenium
# [llm|browser|blog|generic]  llm is not yet supported
agent-type: browser
# Optional [generate-video|generate-text|post|test|custom|unlisted]
agent-tags: post
form-field-source: $TEXT_FILE
stages:
  login:
    url: https://www.reddit.com/login/
    stage-items:
      enter-user-name:
        search-for: //*[@id="login-username"]
        actions: enter_text $REDDIT_USER_NAME
      enter-password:
        search-for: //*[@id="login-password"]
        actions:
          - enter_text $REDDIT_USER_PASS
          - wait 2 # The button becomes clickable after both are entered
      submit-login:
        search-for:
          shadow-attributes: slot=primaryButton
        actions:
          - click
          - wait 7 # Login takes a while
  cookies:
    stage-items:
      reject-non-essential-cookies:
        events:
          onerror: continue
        search-for:
          shadow-attributes: id=reject-nonessential-cookies-button
        actions:
          - click
          - wait 2
  dismiss-cookie-alert:
    url: https://www.reddit.com/r/${REDDIT_COMMUNITY_NAME}/submit
    stage-items:
      reject-non-essential-cookies:
        timeout-seconds: 10
        events:
          onerror: continue
        search-for:
          - //*[@id="SHORTCUT_FOCUSABLE_DIV"]/div[3]/div/section/div/section[2]/section[2]/form/button
          - //*[@id="SHORTCUT_FOCUSABLE_DIV"]//form/button[contains(text(), "Reject")]
          - //button[contains(text(), "Reject non-essential")]
  title:
    url: https://www.reddit.com/r/${REDDIT_COMMUNITY_NAME}/submit
    stage-items:
      enter-title:
        search-for:
          shadow-attributes: id=innerTextArea
        actions: enter_text $TEXT_TITLE
  cover-image:
    events:
      onerror: continue
    stage-items:
      add-cover-image:
        search-for:
#          - //*[@id="post-composer_bodytext"]/shreddit-composer/rte-toolbar-button-image//input
          shadow-attributes: type=file data-media-type=image
        actions:
          - enter_text $IMAGE_FILE_LANDSCAPE
          - wait 5
      enter-cover-image-caption:
        search-for:
          shadow-attributes: type=text placeholder="Add a caption"
        actions:
          - enter_text $TEXT_TITLE
          - wait 2
  content:
    stage-items:
      enter-content:
        search-for:
          shadow-attributes: name=body contenteditable=true role=textbox
        actions:
          - move_to_element
          - enter
          - enter_text $TEXT_CONTENT
          - wait 2
  post:
    stage-items:
      post-content:
        search-for:
          shadow-attributes: id=inner-post-submit-button type=button
        actions:
          # This is necessary, because the button is usually not visible, after pasting the content
          # move_to_element should scroll the element into view
          - move_to_element
          - wait 2
          - click
          - wait 10
  approve-post:
    url: https://www.reddit.com/r/mod/
    events:
      onstart: run_stages dismiss-cookie-alert
      onerror: log WARNING \n= = = = = = = FAILED TO APPROVE POST (Please do it manually) = = = = = = =\n
    stage-items:
      click-approve-button:
        search-for:
          - //*[@data-testid="post-container"]/*[contains(text(), "${TEXT_TITLE}")]//button[text()="approve"]
          - //*[@data-testid="post-container"]/*[contains(text(), "${TEXT_TITLE}")]//button[starts-with(@id, "ModToolsFlatlist-Approve")]
          - //*[starts-with(@id, "t3_1")]/div[3]/div[4]/div[2]/div[2]//button
        actions:
          - click
          - wait 2
