# [llm|browser|blog|generic]  llm is not yet supported
agent-type: browser
# Optional [generate-video|generate-text|post|test|custom]
agent-tags: test
# Optional [visible|undetected]
#browser-mode: undetected
depends-on:
  - youtube
clear-output-dir: false
stages:
  login:
    events:
      onstart: run_stages youtube.login
      onerror: log ERROR Failed to login to YouTube
      onsuccess: log INFO Logged in to YouTube
#  subtitles:
#    events:
#      onstart: run_stages youtube.subtitles
#      onerror: log ERROR Failed to add subtitles to YouTube video
#      onsuccess: log INFO Subtitles added to YouTube video
