# Facebook ids (starting with 'u_' or 'mount_') are dynamic,
# so we use starts-with to match the first part of the id
stages:
  login:
    url: https://www.facebook.com/
    stage-items:
      decline-optional-cookies:
        events:
          onerror: continue
        search-for:
          - //*[starts-with(@id, "u_0_j_")]
          - //*[@id="facebook"]//button[contains(text(), "cookies")]
      fill-username:
        search-for: //*[@id="email"]
        actions: enter_text $facebook.user.name
      fill-password:
        search-for: //*[@id="pass"]
        actions: enter_text $facebook.user.pass
      click-login:
        search-for:
          - //*[starts-with(@id, "u_0_2_")]/div[2]/button[contains(text(), "Log")]
          - //*[starts-with(@id, "u_0_2_")]//button[contains(text(), "Log")]
          - //*[starts-with(@id, "u_0_5_")]
      wait-till-logged-in:
        events:
          onerror: continue
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[2]/div[1]/a
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[2]/div[1]/a/*[name()="svg"]
          - //*[starts-with(@id, "mount_0_0_")]//a
          - //*[starts-with(@id, "mount_0_0_")]//a/*[name()="svg"]
        actions: none
  post-content:
    url: https://www.facebook.com/me/ # Takes us to the current logged-in user profile
    stage-items:
      click-post-textarea:
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//span[contains(text(), "on your mind")]
          - //*[starts-with(@id, "mount_0_0_")]//*[contains(text(), "on your mind")]
        actions:
          - move_to_element
          - enter
      display-add-photo-or-video-options: # same input accepts either photo or video
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//form//*[@aria-label="Photo/video"]
          - //*[starts-with(@id, "mount_0_0_")]//*[@aria-label="Photo/video"]
      add-video-or-cover-photo:
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//form//input[@type="file"]
          - //*[starts-with(@id, "mount_0_0_")]//input[@type="file"]
        actions:
          # Use the first result from the specified pictory download stage
          #- enter_text $results.pictory.save-downloaded-video.save-file[0]
          - get_first_file ${agents.dir}/pictory/results/save-downloaded-video/save-file $video.output.type
          - enter_text $results.me[0]
          - wait 5
      enter-post-text:
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//form//div[@role="textbox"]
          - //*[starts-with(@id, "mount_0_0_")]//*[@role="textbox"]
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/form/div/div[1]/div/div/div/div[2]/div[1]/div[1]/div[1]/div/div/div[1]
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/form/div/div[1]/div/div/div/div[2]/div[1]/div[1]/div[1]/div/div/div[1]/p
        actions:
          - enter_text $video.description
          - wait 2
      submit-post:
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//form//div[@aria-label="Post"]
          - //*[starts-with(@id, "mount_0_0_")]//*[@aria-label="Post"]
          - //*[starts-with(@id, "mount_0_0_")]//*[contains(text(), "Post")]
        actions:
          - click
          - wait 10
