define:
  &default_wait 'wait 3'
interval-seconds: 1
stages:
  login:
    url: https://app.pictory.ai/login
    stage-items:
      username:
        search-for: //*[@id="mui-1"]
        actions: enter_text $PICTORY_USER_EMAIL
      password:
        search-for: //*[@id="outlined-adornment-password"]
        actions: enter_text $PICTORY_USER_PASS
      submit-login:
        search-from: //form
        search-for: //*[@type="submit"]
        actions:
          - click
          - *default_wait
  script-input:
    url: https://app.pictory.ai/textinput
    events:
      on_error:
        - *default_wait
        - retry 1
    stage-items:
      select-script-input:
        search-for:
          - //*[@id="root"]//button[contains(text(), "Proceed")]
          - //*[@id="root"]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[3]/button
          - //*[@id="root"]/div[1]/div[4]/div[1]/div[3]/div[1]/div[1]/div[3]/button
      title:
        search-for:
          - //*[@id="root"]//*[@role="textbox"]/preceding-sibling::*/input
          - //*[@id="root"]/div[1]/div[3]/div/main/div/div/div[4]/input
          - //*[@id="root"]/div[1]/div[4]/div/main/div/div/div[4]/input
        actions: enter_text $VIDEO_TITLE
      text:
        search-for:
          - //*[@id="root"]//*[@role="textbox"]
          - //*[@id="root"]/div[1]/div[3]/div/main/div/div/div[5]
          - //*[@id="root"]/div[1]/div[4]/div/main/div/div/div[5]
        actions:
          - enter_text $VIDEO_INPUT_TEXT
          # Without this we got redirected back probably because
          # submit button is only enabled a short while after entering text
          - wait 5
      script-input-submit:
        search-for:
          - //*[@id="root"]//button[contains(text(), "Proceed")]
          - //*[@id="root"]/div[1]/div[3]/div/main/div/div/div[2]/span[2]/div/div[2]/button[contains(text(), "Proceed")]
          - //*[@id="root"]/div[1]/div[4]/div/main/div/div/div[2]/span[2]/div/div[2]/button[contains(text(), "Proceed")]
        actions:
          - click
          - wait 15 # TODO - Change to 30, also check if we even need this
  pre-post:
    url: https://app.pictory.ai/storyboard/scripttovideo
    events:
      onerror: continue
    stage-items:
      close-app-cues:
        search-for:
          - /html/body/appcues/div/a
          - /html/body/appcues//*[@aria-label="Close modal"]
  add-cover-image:
    url: https://app.pictory.ai/storyboard/scripttovideo
    events:
      onerror: continue
    stage-items:
      select-first-scene:
        search-for:
          - //*[@id="AllSceneTitleText_1_1"]
          - //*[@id="AllSceneTitleText_1_1"]/span[1]
          - //*[contains(text(), "Scene 1")]
      select-visuals-tab:
        search-for:
          - //*[@id="visuals"]
          - //*[@id="side-navbar"]/ul/li[contains(text(), "Visuals") or contains(text(), "visual")]
      select-uploads-button:
        search-for:
          - //*[@id="step-3-fixed-height"]//button[contains(text(), "uploads")]
          - //*[@id="step-3-fixed-height"]/div[1]/div/div[2]/div[1]/div[1]/div/div/div/button[contains(text(), "uploads")]
          - //*[@role="tablist"]//button[contains(text(), "uploads")]
      enter-cover-image:
        search-for:
          - //*[@id="file"]
          - //*[@id="tbinner-3"]//form/div/input[@type="file"]
        actions:
          - enter_text $VIDEO_COVER_IMAGE
          - wait 2
  save-cover-image:
    stage-items:
      click-save:
        expected:
          actions: not is_displayed
        events:
          onerror: retry 1
        search-for:
          - //*[@id="UploadImageModel"]/div/div/div/div[2]/div[2]/button[contains(text(), "Save")]
          - //*[@id="UploadImageModel"]//*[contains(text(), "Save")]
        actions:
          - click
          - wait 15 # Actual upload happens here
  select-saved-cover-image:
    stage-items:
      select-saved-cover:
        search-for:
          - //*[@id="tbinner-3"]//div[@role="rowgroup"]/div[2]
          - //*[@id="tbinner-3"]//div[@role="rowgroup"]/div[2]/div/div[1]/a
          - //*[@id="tbinner-3"]//div[@role="rowgroup"]/div[2]/div/div[1]/a/div
          - //*[@id="tbinner-3"]//div[@role="rowgroup"]/div[2]/div/div[1]/a/div/img
  audio:
    event:
      onerror: continue
    stage-items:
      select-audio-tab:
        search-for:
          - //*[@id="side-navbar"]/ul/li/a/*[contains(text(), "Audio")]//..
          - //*[@id="side-navbar"]//*[contains(text(), "Audio")]//..
      select-volume:
        search-for:
          - //*[@id="step-3-fixed-height"]//div[@role="tablist"]/button[contains(text(), "Volume")]
          - //*[@id="step-3-fixed-height"]//*[contains(text(), "Volume")]
      move-volume-slider:
        search-for:
          - //*[@id="bgMusicVolPercent"]
          - //*[@id="voice-tabpanel-settings"]//div[contains(@class, "volume-slider")]
        actions:
          - move_to_element_offset bottom-left 10% 20%
          - wait 2
          - click_and_hold_current_position
          - wait 1
          - move_by_offset 0 32
          - wait 1
  branding:
    stage-items:
      branding-tab:
        search-for:
          - //*[@id="templates-tab"]
          - //*[@id="side-navbar"]/ul/li/a/*[contains(text(), "Branding")]//..
          - //*[@id="side-navbar"]//*[contains(text(), "Branding")]//..
      expand-brand-options:
        search-for: //*[@id="step-3-fixed-height"]/div[1]/div/div[6]/div/div[1]/div[1]/div/div/div
      select-brand:
        # We first identify the brand by its name, then we work upwards to the selectable element
        search-for:
          - //*[@id="menu-"]/div[3]/ul/li[2]/div/div/div[2]/span[contains(text(), "${PICTORY_BRAND_NAME}")]//..//..//..//..
          - //*[@id="menu-"]//ul/li//span[contains(text(), "${PICTORY_BRAND_NAME}")]//..//..//..//..
      accept-brand-changes-prompt:
        events:
          onerror: continue
        search-for: /html/body//*[@role="dialog"]//button[contains(text(), "Continue")]
      select-brand-background-music:
        search-for: //*[@id="step-3-fixed-height"]//span[contains(text(), "${PICTORY_BG_MUSIC_NAME}")]//..
        actions:
          - click
          - wait 3
      select-brand-voice:
        search-for: //*[@id="step-3-fixed-height"]//span[contains(text(), "${PICTORY_VOICE_NAME}")]//..
        actions:
          - move_to_element_offset bottom-right -5 6
          - wait 1
          - click_and_hold_current_position
          - wait 0.5
          - release false
          # After clicking an alert is displayed for a few seconds informing us of changes
          # After the first alert another is displayed when the changes have been applied
          # The second alert is handled by the next target
      dismiss-brand-voice-notice:
        events:
          onerror: continue
        # There will be some default waiting for this element to appear
        wait-timeout-seconds: 120
        search-for: //*[contains(text(), "Voiceover applied")]
        actions: wait 2
  download-video:
    stage-items:
      expand-download-options:
        search-for: //*[@id="generate-button-dropdown"]/a
        actions:
          - move_to_element
          - wait 3
      select-video-download:
        events:
          onerror:
            - dismiss_alert 5
            - retry 1
        search-for: //*[@id="btnGenerate"]
      begin-download:
        wait-timeout-seconds: 600
        search-for:
          - /html/body//div[@role="dialog"]//button[contains(text(), "Download")]
        actions:
          - click
          - *default_wait
      close-download-notice:
        search-for:
          - /html/body//div[@role="dialog"]//*[name()="svg"]
        actions:
          - click
          - wait 2
          - dismiss_alert 10
          - wait 2
      close-download-alert:
        when:
          search-for:
            - //*[@id="notification-bell-dropdown"]//span[contains(text(), "Notifications")]//..
            - //*[@id="notification-bell-dropdown"]/ul//span[contains(text(), "Notifications")]//..
          actions: is_displayed
        search-for: //*[@id="notification-bell-dropdown"]
        actions:
          - click
          - wait 2
  save-downloaded-video:
    stage-items:
      save-file:
        # By saving the file, other agents may access it from the local disc
        # event when pictory run context is no longer available
        # Will be saved to /pictory-dir/stage/stage-item/original-file-name.extension
        # E.g. main/resources/agent/pictory/results/save-downloaded-video/save-file/original.mp4
        actions:
          - wait 10 # Wait to make sure the file is downloaded
          - get_newest_file_in_dir ${OUTPUT_DIR}/pictory $VIDEO_OUTPUT_TYPE 120
          - save_file $results.me[1]
  download-video-layout-2:
    events:
      onsuccess: run_stages download-video save-downloaded-video
    stage-items:
      expand-layout-2-options:
        search-for:
          - //*[@id="step-3-fixed-height"]/div[2]/div[1]/div/div[2]/div/div/div[2]/div/div/div
          - //*[@id="step-3-fixed-height"]//div[@role="combobox"]
      select-layout-2:
        search-for:
          - //*[@id="menu-"]//ul/li[contains(text(), "Portrait")]
          - //*[@id="menu-"]//ul/li[2]
        actions:
          - click
          - wait 6  # An 8 mb video took 2 seconds
  download-video-layout-3:
    events:
      onsuccess: run_stages download-video save-downloaded-video
    stage-items:
      expand-layout-3-options:
        search-for: $self.stages.download-video-layout-2.stage-items.expand-layout-2-options.search-for
      select-layout-3:
        search-for:
          - //*[@id="menu-"]//ul/li[contains(text(), "Square")]
          - //*[@id="menu-"]//ul/li[3]
        actions:
          - click
          - wait 6  # An 8 mb video took 2 seconds
  download-subtitles:
    url: https://app.pictory.ai/myvideos
    stage-items:
      select-uploaded-video-project:
        search-for:
          - //*[@id="h-tb1"]//div[@class="inner-vdbox"]
          - //*[@id="h-tb1"]//img[@alt="${VIDEO_TITLE}"]
          - //*[@id="h-tb1"]//img[@alt="${VIDEO_TITLE}"]//..
          - //*[@id="h-tb1"]//img[@alt="${VIDEO_TITLE}"]//..//..
      download-subtitles-file:
        events:
          onerror:
            - log WARNING \n= = = = = = = FAILED TO DOWNLOAD SUBTITLES (Please do it manually) = = = = = = =\n
            - continue
        wait-timeout-seconds: 7
        #search-from: //*[@id="h-tb1"]//div[contains(text(), "${TRANSLATION_FILE_EXTENSION}")]
        #search-for: //*[name()="svg"]
        search-for:
          - //*[@id="h-tb1"]/div/div/div/div/div/div[4]/div/div/div/div/div/div[2]/div[2]/*[name()="svg"]
          - //*[@id="h-tb1"]//span[contains(text(), "${TRANSLATION_FILE_EXTENSION}")]//..//..//..//..//*[name()="svg"]
        actions:
          - click
          - wait 5