# [llm|browser|blog|generic]  llm is not yet supported
agent-type: blog
# Optional [generate-video|generate-text|post|test|custom]
agent-tags: post
app:
  name: automate-jamstack
  version: 0.1.4
  docker:
    image: poshjosh/${self.app.name}
  source:
    url: https://github.com/poshjosh/${self.app.name}/archive/refs/tags/v${self.app.version}.zip
  target:
    dir: ${BLOG_APP_DIR}/app
  base:
    # Downloading and extracting app.source.url will create this directory
    dir: ${BLOG_APP_DIR}/app/${self.app.name}-${self.app.version}
  script:
    convert-to-markdown: ${BLOG_APP_DIR}/app/${self.app.name}-${self.app.version}/scripts/convert-to-markdown.sh
    update-blog: ${BLOG_APP_DIR}/app/${self.app.name}-${self.app.version}/scripts/docker-run-app.sh
    docker-entrypoint: ${BLOG_APP_DIR}/app/${self.app.name}-${self.app.version}/app/config/setup-scripts/docker-entrypoint.sh
blog:
  name: liveabove3d.com
  language-codes: $LANGUAGE_CODES
  source:
    url: https://github.com/poshjosh/${self.blog.name}.git
  target:
    # git clone blog.src.url will create and populate this directory
    dir: ${BLOG_APP_DIR}/blogs/${self.blog.name}
alternate-source: $TEXT_FILE
alternate-title: $TEXT_TITLE
alternate-source-image: $IMAGE_FILE_LANDSCAPE
stages:
  download-app:
  clone-blog:
  convert-to-markdown:
  update-blog-content:
  update-blog:
    timeout-seconds: 1800
