#############################################################
# Facebook ids (starting with 'u_' or 'mount_') are dynamic,
# so we use starts-with to match the first part of the id
#############################################################
# [llm|browser|blog|generic]  llm is not yet supported
agent-type: browser
# Optional [generate-video|generate-text|post|test|custom]
agent-tags: post
post-dialog: //*[starts-with(@id, "mount_0_0_")]//*[@role="dialog"]
stages:
  login:
    url: https://www.facebook.com/
    stage-items:
      decline-optional-cookies:
        events:
          onerror: continue
        search-for:
          - //*[starts-with(@id, "u_0_j_")]
          - //*[@id="facebook"]//button[contains(text(), "cookies")]
      fill-username:
        search-for: //*[@id="email"]
        actions: enter_text $FACEBOOK_USER_EMAIL
      fill-password:
        search-for: //*[@id="pass"]
        actions: enter_text $FACEBOOK_USER_PASS
      click-login:
        search-for:
          - //*[starts-with(@id, "u_0_5_")]
          - //*[starts-with(@id, "u_0_2_")]/div[2]/button[contains(text(), "Log")]
          - //*[starts-with(@id, "u_0_2_")]//button[contains(text(), "Log")]
      wait-till-logged-in:
        events:
          onerror: continue
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[2]/div[1]/a
          - //*[starts-with(@id, "mount_0_0_")]/div/div[1]/div/div[2]/div[1]/a/*[name()="svg"]
          - //*[starts-with(@id, "mount_0_0_")]//a
          - //*[starts-with(@id, "mount_0_0_")]//a/*[name()="svg"]
        actions: none
  post-content:
    url: https://www.facebook.com/me/ # Takes us to the current logged-in user profile
    stage-items:
      click-post-textarea:
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//span[contains(text(), "on your mind")]
          - //*[starts-with(@id, "mount_0_0_")]//*[contains(text(), "on your mind")]
        actions:
          - move_to_element
          - wait 3
          - click
      display-add-photo-or-video-options: # same input accepts either photo or video
        search-for:
          - //*[starts-with(@id, "mount_0_0_")]//form//*[@aria-label="Photo/video"]
          - //*[starts-with(@id, "mount_0_0_")]//*[@aria-label="Photo/video"]
      add-video-or-cover-photo:
        search-for:
          - ${self.post-dialog}//form//input[@type="file"]
          - ${self.post-dialog}//input[@type="file"]
        actions:
          - enter_text $VIDEO_FILE_LANDSCAPE
          - wait 10
      enter-post-text:
        search-for:
          - ${self.post-dialog}//form//div[@role="textbox"]
          - ${self.post-dialog}//*[@role="textbox"]
        actions:
          - enter_text $TEXT_CONTENT
          - wait 10 # Long posts take a while
      submit-post:
        search-for:
          - ${self.post-dialog}//form//div[@aria-label="Post"]
          - ${self.post-dialog}//*[@aria-label="Post"]
          - ${self.post-dialog}//*[contains(text(), "Post")]
        actions:
          - click
          - wait 10
