# Instagram ids (starting with 'u_' or 'mount_') are dynamic,
# so we use starts-with to match the first part of the id
# [llm|browser|blog|generic]  llm is not yet supported
agent-type: browser
# Optional [generate-video|generate-text|post|test|custom]
agent-tags: post
depends-on:
  - facebook
stages:
  # Direct login did not work for me, probably 'cos I signed up via facebook
  # So, after this stage, we add a stage to login via facebook
  login:
    url: https://www.instagram.com/
    events:
      onerror: continue
    stage-items:
#      expand-language-options:
#        events:
#          onerror: continue
#        search-for:
#          - /html/body//select[@aria-label="Switch display language"]//..
#          - /html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[1]/span
#      select-language:
#        events:
#          onerror: continue
#        search-for:
#          - /html/body//select[@aria-label='Switch display language']/option[@value='en']
      decline-optional-cookies:
        events:
          onerror: continue
        search-for:
          - /html/body//button[contains(text(), 'optional cookies')]
          - /html/body//button[contains(text(), 'cookies')]
          - /html/body/div[4]/div[1]/div/div[2]/div/div/div/div/div[2]/div/button[contains(text(), 'cookies')]
          - /html/body/div[4]/div[1]/div/div[2]/div/div/div/div/div[2]/div/button[2]
      username:
        search-for:
          - //*[@id="loginForm"]/div/div[1]/div/label/input
          - //*[@id="loginForm"]//input[@name="username"]
        actions: enter_text $INSTAGRAM_USER_EMAIL
      password:
        search-for:
          - //*[@id="loginForm"]/div/div[2]/div/label/input
          - //*[@id="loginForm"]//input[@name="password"]
        actions: enter_text $INSTAGRAM_USER_PASS
      submit:
        search-for:
          - //*[@id="loginForm"]/div/div[3]/button
          - //*[@id="loginForm"]//button[@type="submit"]
        actions:
          - click
          - wait 7
  # Facebook login page, after redirect from instagram login, displays url:        -
  # https://www.facebook.com/login.php?skip_api_login=1&api_key=124024574287414&kid_directed_site=0&app_id=124024574287414&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Foauth%3Fclient_id%3D124024574287414%26locale%3Den_GB%26redirect_uri%3Dhttps%253A%252F%252Fwww.instagram.com%252Faccounts%252Fsignup%252F%26response_type%3Dcode%252Cgranted_scopes%26scope%3Demail%26state%3D%257B%2522fbLoginKey%2522%253A%2522rc8dad1d9l7sa11p3w3fwp8s881dljjum1g8ajym19uq20v1vjmuj%2522%252C%2522fbLoginReturnURL%2522%253A%2522%252Ffxcal%252Fdisclosure%252F%253Fnext%253D%25252F%2522%257D%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3D70f94558-f628-4b9f-88d7-6ab20047953b%26tp%3Dunspecified&cancel_url=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fsignup%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D%257B%2522fbLoginKey%2522%253A%2522rc8dad1d9l7sa11p3w3fwp8s881dljjum1g8ajym19uq20v1vjmuj%2522%252C%2522fbLoginReturnURL%2522%253A%2522%252Ffxcal%252Fdisclosure%252F%253Fnext%253D%25252F%2522%257D%23_%3D_&display=page&locale=en_GB&pl_dbl=0
  login-via-facebook:
    when:
      # When the submit button from above is displayed
      search-for:
        - $self.stages.login.stage-items.submit.search-for[0]
        - $self.stages.login.stage-items.submit.search-for[1]
      actions: is_displayed
    events:
      onstart: run_stages facebook.login
      onsuccess: wait 7
      onerror:
        - wait 2
        - retry 1
  if-still-not-logged-in:
    url: https://www.instagram.com/
    events:
      # If we have successfully logged in, then this will have an error; we simply continue
      onerror: continue
    stage-items:
      # After successful login via facebook, we are redirected to instagram
      # where we often have to click login via facebook once-again before we
      # are navigated to the dashboard
      proceed-to-facebook-login:
        search-for:
          - //*[@id="loginForm"]/div/div[5]
          - //*[@id="loginForm"]/div/div[5]/button[contains(text(), "Facebook")]
          - //*[@id="loginForm"]//button[contains(text(), "Facebook")]
        actions:
          - click
          - wait 7
      # At this point we are presented with a button by facebook to Continue to instagram.
      # We click the button
      login-via-facebook:
        search-for:
          - //*[@id="platformDialogForm"]//button[@name="__CONFIRM__" and @type="submit" and contains(text(), "Continue")]
          - //*[@id="platformDialogForm"]//*[contains(text(), "Continue")]
  dismiss-notifications-alert:
#    url: https://www.instagram.com/
    events:
      onerror: continue
    stage-items:
      dismiss-notifications:
        search-for:
          - /html/body//div[@role="dialog"]//button[contains(text(), 'Not Now')]
          - /html/body//button[contains(text(), 'Not Now')]
          - /html/body//div[@role="dialog"]//button[2]
  proceed-to-post:
    stage-items:
      click-create:
        search-for:
          - //*[starts-with(@id,"mount_0_0_")]/div/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div[2]/div[7]//a
          - //*[starts-with(@id,"mount_0_0_")]/div/div/div[2]/div/div/div[1]/div[1]/div[1]/div/div/div/div/div[2]/div[7]/div/span/div/a
          - //*[starts-with(@id,"mount_0_0_")]//*[text()="Create"]//..//..//..//..//..//..
      add-video:
        search-for:
          - //form[@enctype="multipart/form-data"]/input[@type="file"]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[2]/div[1]/form/input
          - /html/body//form/input[@type="file"]
          - //input[@type="file"]
        actions:
          - enter_text $VIDEO_FILE_SQUARE
          - wait 7
      dismiss-alert:
        events:
          onerror: continue
        search-for:
          - /html/body//div[@role="dialog"]//button[contains(text(), 'OK')]
          - /html/body//div[@role="dialog"]//button
          - /html/body/div[6]/div[2]/div/div/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/div/div[4]/button
      proceed-to-edit:
        search-for:
          - /html/body//div[@role="dialog"]//div[contains(text(), "Next")]
          - /html/body//div[@role="dialog"]//*[contains(text(), "Next")]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div/div
# The first scene (which is the cover-photo) is used if cover photo is not uploaded
# We observed that the first scene looked better than when we uploaded a cover photo.
#      add-cover-photo:
#        events:
#          onerror: continue
#        search-for:
#          - //div[@role="dialog"]//form[@enctype="multipart/form-data"]/input[@type="file"]
#          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[1]/div[1]/div/div/form/input
#          - //div[@role="dialog"]//form/input[@type="file"]
#        actions:
#          - enter_text $IMAGE_FILE_SQUARE
#          - wait 15
      proceed-to-content:
        search-for:
          - /html/body//div[@role="dialog"]//div[contains(text(), "Next")]
          - //div[@role="dialog"]//*[contains(text(), "Next")]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div/div
      enter-content:
        search-for:
          - /html/body//div[@role="dialog"]//div[@role="textbox"]
          - //div[@role="dialog"]//*[@role="textbox"]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[2]/div[2]/div/div/div/div[1]/div[2]/div/div[1]/div[1]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[2]/div[2]/div/div/div/div[1]/div[2]/div/div[1]/div[1]/p
        actions: enter_text $TEXT_CONTENT
      submit:
        search-for:
          - /html/body//div[@role="dialog"]//div[contains(text(), "Share")]
          - /html/body//div[@role="dialog"]//*[contains(text(), "Share")]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div
          - /html/body/div[6]/div[1]/div/div[3]/div/div/div/div/div/div/div/div[1]/div/div/div/div[3]/div/div
      wait-till-posted:
        timeout-seconds: 120 # Upload of a 34mb 50 seconds video took about 60 seconds
        events:
          onerror: continue
        search-for:
          - /html/body//div[@role="dialog"]//h1/div[contains(text(), "Reel shared")]
          - /html/body//div[@role="dialog"]//h1/*[contains(text(), "shared")]
          - /html/body//div[@role="dialog"]//span[contains(text(), 'shared')]
          - /html/body//div[@role="dialog"]//*[contains(text(), 'shared')]
        actions: none
