# [llm|browser|blog|generic]  llm is not yet supported
agent-type: browser
# Optional [generate-video|generate-text|post|test|custom]
agent-tags:
  - test
  - post
stages:
  cookies:
    url: https://www.reddit.com/
    stage-items:
      reject-non-essential-cookies:
        events:
          onerror: continue
        search-for:
          shadow-attributes: id=reject-nonessential-cookies-button
        actions:
          - click
          - wait 2
