browser:
  chrome:
    undetected: true
    options:
      args:
        - user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
        # Use either (headless and start-maximized) or kiosk
        # Trying to change window size, while using kiosk, will crash the driver
        # Without this custom window size, we got ElementNotInteractableException
        # Window size should match that in docker-entrypoint.sh
        - window-size=1920,1080
        - start-maximized
depends-on:
  - youtube
clear-output-dir: false
stages:
  login:
    events:
      onstart: run_stages youtube.login
      onerror: log ERROR Failed to login to YouTube
      onsuccess: log INFO Logged in to YouTube
#  subtitles:
#    events:
#      onstart: run_stages youtube.subtitles
#      onerror: log ERROR Failed to add subtitles to YouTube video
#      onsuccess: log INFO Subtitles added to YouTube video
